### PR TITLE
Keep schema definition in sync with latest update hook.

### LINKED ISSUE #9: DB schema for cmrf_core_call incorrect for request and reply columns
In 07d80b4d7b71c1476b618bab9f94b4e4ac15eb87, `NOT NULL` was set to `TRUE`, which is

- inconsistent with the latest hook_update_N() in the Drupal module (See commit 4862cd1f403f9acc44e0eff1c7ba84968891978c)
- conceptually wrong and leads to default value exceptions on new installations

Proposed fix is to set `NOT NULL` for `request` and `reply` columns to `FALSE`.

### PR DESCRIPTION
**Pull request by jensschuppe**
Fixes #9.

### CODE REVIEW

**Comment by jensschuppe** [comment]
@jaapjansma Could you have a look? I think this removes the inconsistencies between AbstractCore and the Drupal module correctly, but did not test with a new module installation.

**Comment by jaapjansma** [comment]
Looks good to me. I cannot think why this change could break something.

**Comment by jensschuppe** [comment]
@jaapjansma Thanks! Could you merge this PR then? I do not have write access to the repository.

P.S. Just a thought: Maybe it's not the best thing having Drupal `hook_schema()` code within CMRF_Abstract_Core. This could be abstracted and the Drupal module may implement `hook_requirements()` to check for the correct supported version of CMRF_Abstract_Core, so that there are no inconsistencies between the DB schemas.

**Comment by jaapjansma** [comment]
I agree on your PS. Drupal core should take care of the schema. In this class we would rather only have the ability to store calls.

**Pull request merged**
